### ISSUE TITLE
Add the supports for other viruses genome

### ISSUE THREAD

**Issue by nhhaidee** [CFIA-NCFAD/wgscovplot#3]
In the development phase, the tool is designed for SARS-COV2 virus. The supports for other virus such as Avian Influenza, African Swine Fever Virus (ASFV), Foot and Mouth Disease (FMD) should be implemented

**Comment by nhhaidee** [comment]
Child of https://github.com/nhhaidee/wgscovplot/issues/6

**Comment by peterk87** [comment]
Since nf-core/viralrecon and CFIA-NCFAD/nf-virontus support different non-segmented viruses and wgscovplot supports the output of those tools, wgscovplot should support various viruses. The only segmented viruses supported by wgscovplot are Influenza A and B viruses and only if the analysis results are generated by CFIA-NCFAD/nf-flu as of wgscovplot 1.0.0.
